/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mwora
 */
public class BUTACAS1 extends javax.swing.JFrame {

    /**
     * Creates new form BUTACAS1
     */
    public BUTACAS1() {
        initComponents();
    }
    
    public static int cantidadBoletos;
    public static int precioTotalBoletos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boletosReservados = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JLabel();
        butaca5 = new javax.swing.JButton();
        butaca1 = new javax.swing.JButton();
        butaca4 = new javax.swing.JButton();
        butaca6 = new javax.swing.JButton();
        butaca2 = new javax.swing.JButton();
        butaca7 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        butaca3 = new javax.swing.JButton();
        butaca9 = new javax.swing.JButton();
        butaca8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FIVE NI.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 248, 96));

        boletosReservados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boletosReservados.setForeground(new java.awt.Color(0, 0, 0));
        boletosReservados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boletosReservados.setText("0");
        jPanel1.add(boletosReservados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 280, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Boletos Reservados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 393, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PRECIO TOTAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        precioTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(0, 0, 0));
        precioTotal.setText("0");
        jPanel1.add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        butaca5.setBackground(new java.awt.Color(51, 255, 51));
        butaca5.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca5.setForeground(new java.awt.Color(255, 255, 255));
        butaca5.setText("A3");
        jPanel1.add(butaca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 80));

        butaca1.setBackground(new java.awt.Color(51, 255, 51));
        butaca1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca1.setForeground(new java.awt.Color(255, 255, 255));
        butaca1.setText("A1");
        butaca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butaca1MousePressed(evt);
            }
        });
        butaca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaca1ActionPerformed(evt);
            }
        });
        jPanel1.add(butaca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 80));

        butaca4.setBackground(new java.awt.Color(51, 255, 51));
        butaca4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca4.setForeground(new java.awt.Color(255, 255, 255));
        butaca4.setText("A2");
        butaca4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butaca4MousePressed(evt);
            }
        });
        jPanel1.add(butaca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 80));

        butaca6.setBackground(new java.awt.Color(51, 255, 51));
        butaca6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca6.setForeground(new java.awt.Color(255, 255, 255));
        butaca6.setText("B1");
        jPanel1.add(butaca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 80));

        butaca2.setBackground(new java.awt.Color(51, 255, 51));
        butaca2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca2.setForeground(new java.awt.Color(255, 255, 255));
        butaca2.setText("B2");
        butaca2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butaca2MousePressed(evt);
            }
        });
        jPanel1.add(butaca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, 80));

        butaca7.setBackground(new java.awt.Color(51, 255, 51));
        butaca7.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca7.setForeground(new java.awt.Color(255, 255, 255));
        butaca7.setText("B3");
        jPanel1.add(butaca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, 80));

        jButton7.setText("jButton1");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 80));

        jButton8.setText("jButton1");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 80));

        jButton9.setText("jButton1");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 80, 80));

        butaca3.setBackground(new java.awt.Color(51, 255, 51));
        butaca3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca3.setForeground(new java.awt.Color(255, 255, 255));
        butaca3.setText("C3");
        butaca3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                butaca3MousePressed(evt);
            }
        });
        jPanel1.add(butaca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 80, 80));

        butaca9.setBackground(new java.awt.Color(51, 255, 51));
        butaca9.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca9.setForeground(new java.awt.Color(255, 255, 255));
        butaca9.setText("C2");
        jPanel1.add(butaca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, 80));

        butaca8.setBackground(new java.awt.Color(51, 255, 51));
        butaca8.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        butaca8.setForeground(new java.awt.Color(255, 255, 255));
        butaca8.setText("C1");
        jPanel1.add(butaca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, 80));

        jButton2.setText("RESERVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaca1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_butaca1ActionPerformed

    private void butaca1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaca1MousePressed
        // TODO add your handling code here:
        butaca1.setBackground(Color.RED);
        cantidadBoletos++;
        precioTotalBoletos+=80;
        boletosReservados.setText(String.valueOf(cantidadBoletos));
        precioTotal.setText(String.valueOf(precioTotalBoletos));
    }//GEN-LAST:event_butaca1MousePressed

    private void butaca2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaca2MousePressed
        // TODO add your handling code here:
        butaca2.setBackground(Color.RED);
        cantidadBoletos++;
        precioTotalBoletos+=80;
        boletosReservados.setText(String.valueOf(cantidadBoletos));
        precioTotal.setText(String.valueOf(precioTotalBoletos));
    }//GEN-LAST:event_butaca2MousePressed

    private void butaca3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaca3MousePressed
        // TODO add your handling code here:
        butaca3.setBackground(Color.RED);
        cantidadBoletos++;
        precioTotalBoletos+=80;
        boletosReservados.setText(String.valueOf(cantidadBoletos));
        precioTotal.setText(String.valueOf(precioTotalBoletos));
    }//GEN-LAST:event_butaca3MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por reservar en Cinépolis");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butaca4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaca4MousePressed
        // TODO add your handling code here:
         butaca4.setBackground(Color.RED);
        cantidadBoletos++;
        precioTotalBoletos+=80;
        boletosReservados.setText(String.valueOf(cantidadBoletos));
        precioTotal.setText(String.valueOf(precioTotalBoletos));
    }//GEN-LAST:event_butaca4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BUTACAS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BUTACAS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BUTACAS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BUTACAS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BUTACAS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boletosReservados;
    private javax.swing.JButton butaca1;
    private javax.swing.JButton butaca2;
    private javax.swing.JButton butaca3;
    private javax.swing.JButton butaca4;
    private javax.swing.JButton butaca5;
    private javax.swing.JButton butaca6;
    private javax.swing.JButton butaca7;
    private javax.swing.JButton butaca8;
    private javax.swing.JButton butaca9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel precioTotal;
    // End of variables declaration//GEN-END:variables
}
