/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import java.awt.Font;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import Pages.PaginaAsientos;



/**
 *
 * @author mwora
 */
public class PaginaDulceria extends javax.swing.JFrame {

    /**
     * Creates new form PaginaDulceria
     */
    public PaginaDulceria() {
        initComponents();
        
       
    }
     public static int precioTotalDulces;
     public static int cantidadProductos;
     ImageIcon bolsaCompras = new ImageIcon(getClass().getResource("/Images/Compra.png"));
     Font font = new Font("Roboto", Font.BOLD, 19);
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        labelDulceria = new javax.swing.JLabel();
        izquierdaImagen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSnacks1 = new javax.swing.JPanel();
        txtSnacks1 = new javax.swing.JLabel();
        btnSnacks5 = new javax.swing.JPanel();
        txtSnacks5 = new javax.swing.JLabel();
        btnSnacks2 = new javax.swing.JPanel();
        txtSnacks2 = new javax.swing.JLabel();
        btnSnacks6 = new javax.swing.JPanel();
        txtSnacks6 = new javax.swing.JLabel();
        btnSnacks7 = new javax.swing.JPanel();
        txtSnacks7 = new javax.swing.JLabel();
        btnSnacks3 = new javax.swing.JPanel();
        txtSnacks3 = new javax.swing.JLabel();
        btnSnacks4 = new javax.swing.JPanel();
        txtSnacks4 = new javax.swing.JLabel();
        btnSnacks8 = new javax.swing.JPanel();
        txtSnacks8 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JPanel();
        txtAtras = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(51, 102, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDulceria.setFont(new java.awt.Font("Roboto Medium", 1, 70)); // NOI18N
        labelDulceria.setForeground(new java.awt.Color(255, 255, 0));
        labelDulceria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDulceria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DULCERÍA (2).png"))); // NOI18N
        header.add(labelDulceria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/s (1).png"))); // NOI18N

        javax.swing.GroupLayout izquierdaImagenLayout = new javax.swing.GroupLayout(izquierdaImagen);
        izquierdaImagen.setLayout(izquierdaImagenLayout);
        izquierdaImagenLayout.setHorizontalGroup(
            izquierdaImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
        );
        izquierdaImagenLayout.setVerticalGroup(
            izquierdaImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izquierdaImagenLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        background.add(izquierdaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 150, 370));

        btnSnacks1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS.png"))); // NOI18N
        txtSnacks1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks1MouseClicked(evt);
            }
        });
        btnSnacks1.add(txtSnacks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 150));

        btnSnacks5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (4).png"))); // NOI18N
        txtSnacks5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks5MouseClicked(evt);
            }
        });
        btnSnacks5.add(txtSnacks5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 150, 150));

        btnSnacks2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (1).png"))); // NOI18N
        txtSnacks2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks2MouseClicked(evt);
            }
        });
        btnSnacks2.add(txtSnacks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 150, 150));

        btnSnacks6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (5).png"))); // NOI18N
        txtSnacks6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks6MouseClicked(evt);
            }
        });
        btnSnacks6.add(txtSnacks6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, 150));

        btnSnacks7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (6).png"))); // NOI18N
        txtSnacks7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks7MouseClicked(evt);
            }
        });
        btnSnacks7.add(txtSnacks7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 150, 150));

        btnSnacks3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (2).png"))); // NOI18N
        txtSnacks3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks3MouseClicked(evt);
            }
        });
        btnSnacks3.add(txtSnacks3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, 150));

        btnSnacks4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (3).png"))); // NOI18N
        txtSnacks4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks4MouseClicked(evt);
            }
        });
        btnSnacks4.add(txtSnacks4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 150, 150));

        btnSnacks8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSnacks8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SNICKERS (7).png"))); // NOI18N
        txtSnacks8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSnacks8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSnacks8MouseClicked(evt);
            }
        });
        btnSnacks8.add(txtSnacks8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        background.add(btnSnacks8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 150, 150));

        btnAtras.setBackground(new java.awt.Color(255, 102, 204));
        btnAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ATRAS.png"))); // NOI18N
        txtAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAtrasMouseClicked(evt);
            }
        });
        btnAtras.add(txtAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        background.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 310, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAtrasMouseClicked
        new PaginaPrincipal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtAtrasMouseClicked

    private void txtSnacks1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks1MouseClicked
        cantidadProductos++;
        precioTotalDulces += 20;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "Snickers"
                + "\nCantidad: 52.7gr"
                + "\nPrecio: $20"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
        
    }//GEN-LAST:event_txtSnacks1MouseClicked

    private void txtSnacks2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks2MouseClicked
        // TODO add your handling code here:
        cantidadProductos++;
        precioTotalDulces += 60;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "ICEE"
                + "\nCantidad: Grande "
                + "\nPrecio: $60"
                + "\nCompra A ctual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks2MouseClicked

    private void txtSnacks3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks3MouseClicked
        // TODO add your handling code here:
         cantidadProductos++;
        precioTotalDulces += 75;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "Helado Holanda"
                + "\nCantidad: 1L "
                + "\nPrecio: $75"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks3MouseClicked

    private void txtSnacks4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks4MouseClicked
        // TODO add your handling code here:
        cantidadProductos++;
        precioTotalDulces += 20;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "Panditas"
                + "\nCantidad: 300gr"
                + "\nPrecio: $20"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks4MouseClicked

    private void txtSnacks5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks5MouseClicked
        // TODO add your handling code here:
         cantidadProductos++;
        precioTotalDulces += 65;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "Charola Nachos"
                + "\nCantidad: 500gr"
                + "\nPrecio: $65"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks5MouseClicked

    private void txtSnacks6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks6MouseClicked
         cantidadProductos++;
        precioTotalDulces += 35;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "M&Ms Chocolate"
                + "\nCantidad: 50gr"
                + "\nPrecio: 35"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks6MouseClicked

    private void txtSnacks7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks7MouseClicked
         cantidadProductos+=2;
        precioTotalDulces += 90;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "Combo Estudiante"
                + "\nCantidad: 800gr, 800ml "
                + "\nPrecio: $90"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks7MouseClicked

    private void txtSnacks8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSnacks8MouseClicked
         cantidadProductos+=6;
        precioTotalDulces += 220;
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        JOptionPane.showMessageDialog(null, "Combo Jumbo"
                + "\nCantidad: 1.6kg ,2L "
                + "\nPrecio: $220"
                + "\nCompra Actual: $" + precioTotalDulces
                + "\nCantidad Productos:  " + cantidadProductos , "Compra", HEIGHT, bolsaCompras);
    }//GEN-LAST:event_txtSnacks8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaDulceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaDulceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaDulceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaDulceria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaDulceria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnAtras;
    private javax.swing.JPanel btnSnacks1;
    private javax.swing.JPanel btnSnacks2;
    private javax.swing.JPanel btnSnacks3;
    private javax.swing.JPanel btnSnacks4;
    private javax.swing.JPanel btnSnacks5;
    private javax.swing.JPanel btnSnacks6;
    private javax.swing.JPanel btnSnacks7;
    private javax.swing.JPanel btnSnacks8;
    private javax.swing.JPanel header;
    private javax.swing.JPanel izquierdaImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDulceria;
    private javax.swing.JLabel txtAtras;
    private javax.swing.JLabel txtSnacks1;
    private javax.swing.JLabel txtSnacks2;
    private javax.swing.JLabel txtSnacks3;
    private javax.swing.JLabel txtSnacks4;
    private javax.swing.JLabel txtSnacks5;
    private javax.swing.JLabel txtSnacks6;
    private javax.swing.JLabel txtSnacks7;
    private javax.swing.JLabel txtSnacks8;
    // End of variables declaration//GEN-END:variables
}
